# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e7b4a44c82699ef649dcef14870f593b81931bb3fc997cdb350d34ef4381b0c1ef890fcbff6a634d44c5c111bf745738437f5318241b936ff8334c989579e96a

test:
  secret_key_base: 2cdbf1b81b22167f51d5763cf6f15d2008545b3ff24fcbbf721ff9efabf05a629c49ce85410f30b77b6ff3710ab0839097ca418156236684637a721812dc76e8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
